router:
  router:
    configuration:
      # duplicated from ../values.yaml
      health_check:
        listen: 0.0.0.0:8080
      sandbox:
        enabled: true
      homepage:
        enabled: false
      supergraph:
        introspection: true
      include_subgraph_errors:
        all: true
      plugins:
        experimental.expose_query_plan: true
      # end duplication
      telemetry:
        apollo:
          field_level_instrumentation_sampler: 0.5
        tracing:
          otlp:
            endpoint: http://collector.monitoring:4317
            protocol: grpc
          trace_config:
            sampler: 0.5
            service_name: "router"
            service_namespace: "router"
        metrics:
          otlp:
            endpoint: http://collector.monitoring:4317
            protocol: grpc
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
