name: _deploy-router-gcp

# Started from GH Docs
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine

# REQUIRED REPO SECRETS
#   - GCP_CREDENTIALS
#   - CLUSTER_PREFIX
#   - APOLLO_GRAPH_ID
#   - APOLLO_KEY

on:
  workflow_call:
    inputs:
      environment:
        description: "Target variant"
        type: string
        required: true
        default: dev
      variant:
        description: "Target variant"
        type: string
        required: true
        default: dev
      dry-run:
        type: boolean
        description: "Run a dry run with helm"
        required: false
        default: false
      debug:
        type: boolean
        description: "Run helm in debug mode"
        required: false
        default: false
    secrets:
      GCP_CREDENTIALS:
        required: true
      CLUSTER_PREFIX:
        required: true
      APOLLO_GRAPH_ID:
        required: true
      APOLLO_KEY:
        required: true

env:
  GKE_ZONE: us-east1 # Add your cluster zone here.
  CLUSTER_PREFIX: ${{ secrets.CLUSTER_PREFIX }}
  APOLLO_GRAPH_ID: ${{ secrets.APOLLO_GRAPH_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v0

      - name: "Use gcloud CLI"
        run: gcloud info

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.CLUSTER_PREFIX }}-${{ inputs.environment }}
          location: ${{ env.GKE_ZONE }}
          
      - name: Helm dependency update
        run: |
          helm dependency update ./deploy/router

      # Deploy the Docker image to the GKE cluster with dry run
      - name: Helm dry-run
        if: ${{ inputs.dry-run }}
        run: |
          helm upgrade router \
          --create-namespace \
          --namespace router \
          --set router.managedFederation.graphRef=$APOLLO_GRAPH_ID@${{ inputs.variant }} \
          --set router.managedFederation.apiKey=${{ secrets.APOLLO_KEY }} \
          --dry-run \
          --atomic \
          --install \
          ./deploy/router \
          --values ./deploy/router/values.yaml \
          -f ./deploy/router/environments/${{ inputs.environment }}.yaml

      # Deploy the Docker image to the GKE cluster for real with debug
      - name: Deploy
        if: ${{ !inputs.dry-run && inputs.debug }}
        run: |
          helm upgrade router \
          --create-namespace \
          --namespace router \
          --set router.managedFederation.graphRef=$APOLLO_GRAPH_ID@${{ inputs.variant }} \
          --set router.managedFederation.apiKey=${{ secrets.APOLLO_KEY }} \
          --atomic \
          --install \
          --debug \
          ./deploy/router \
          --values ./deploy/router/values.yaml \
          -f ./deploy/router/environments/${{ inputs.environment }}.yaml

      # Deploy the Docker image to the GKE cluster for real
      - name: Deploy
        if: ${{ !inputs.dry-run }}
        run: |
          helm upgrade router \
          --create-namespace \
          --namespace router \
          --set router.managedFederation.graphRef=$APOLLO_GRAPH_ID@${{ inputs.variant }} \
          --set router.managedFederation.apiKey=${{ secrets.APOLLO_KEY }} \
          --atomic \
          --install \
          ./deploy/router \
          --values ./deploy/router/values.yaml \
          -f ./deploy/router/environments/${{ inputs.environment }}.yaml
