replicaCount: 1

image:
  repository: promotions-api
  pullPolicy: Never
  tag: local

nameOverride: api
fullnameOverride: api

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 4010

resources: {}
