{{- if and .Values.ingress.enabled .Values.ingress.gcp -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config
spec:
  healthCheck:
    checkIntervalSec: 15
    port: {{ splitList ":" ((index .Values.router.router.configuration "health_check").listen | default ":8088") | last }}
    type: HTTP
    requestPath: /health
{{- end }}
