image:
  repository: ghcr.io/apollographql/apollo-mcp-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
