# Container image settings
image:
  repository: ghcr.io/apollographql/apollo-mcp-server
  tag: "latest"
  pullPolicy: IfNotPresent

# Service configuration (how to expose the MCP server)
service:
  type: ClusterIP
  port: 8000
  
# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Namespace
namespace: apollo

# DO NOT fill these out here. The shell script will pull your secrets from environment variables
graphos:
  graphRef: ""
  apiKey: ""