#!/bin/bash
set -euo pipefail

# Script 05: Deploy Subgraphs
# This script deploys all subgraphs using Helm and creates Subgraph CRDs with inline SDL.

# Ensure script is run from repository root
if [ ! -d "scripts/minikube" ] || [ ! -d "subgraphs" ] || [ ! -d "deploy" ]; then
    echo "Error: This script must be run from the repository root directory"
    echo "Please run: ./scripts/minikube/05-deploy-subgraphs.sh"
    exit 1
fi

echo "=== Step 05: Deploying Subgraphs ==="

# Load environment variables from .env if it exists
if [ -f .env ]; then
    echo "Loading environment variables from .env..."
    source .env
fi

# Validate required variables
if [[ -z "${ENVIRONMENT:-}" ]]; then
    echo "Error: ENVIRONMENT is required"
    echo "Please set ENVIRONMENT in your .env file or export it:"
    echo "  export ENVIRONMENT=\"dev\""
    exit 1
fi

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "Error: kubectl is not installed"
    exit 1
fi

# Check if helm is available
if ! command -v helm &> /dev/null; then
    echo "Error: helm is not installed"
    exit 1
fi

# Verify cluster connection
if ! kubectl cluster-info &> /dev/null; then
    echo "Error: Cannot connect to Kubernetes cluster"
    exit 1
fi

# List of subgraphs (with GraphQL servers)
SUBGRAPHS=("checkout" "discovery" "inventory" "orders" "products" "reviews" "shipping" "users")

# Connector-only subgraphs (schema only, no deployment - router calls REST APIs directly)
CONNECTOR_SUBGRAPHS=("promotions")

# REST API services (deployed separately from subgraphs)
SERVICES=("promotions-api")

# Deploy each subgraph
for subgraph in "${SUBGRAPHS[@]}"; do
    echo ""
    echo "Deploying ${subgraph}..."
    
    # Create namespace
    kubectl create namespace "${subgraph}" --dry-run=client -o yaml | kubectl apply -f -
    
    # Use environment-specific values file if it exists, otherwise use default
    VALUES_FILE="subgraphs/${subgraph}/deploy/environments/${ENVIRONMENT}.yaml"
    if [ ! -f "$VALUES_FILE" ]; then
        VALUES_FILE="subgraphs/${subgraph}/deploy/values.yaml"
    fi
    
    # Verify values file exists
    if [ ! -f "$VALUES_FILE" ]; then
        echo "Error: Values file not found: $VALUES_FILE"
        exit 1
    fi
    
    # Get image tag from .image-tag file (generated by build script)
    if [ -f ".image-tag" ]; then
        IMAGE_TAG=$(head -n 1 .image-tag | tr -d '[:space:]')
        echo "Using image tag: ${IMAGE_TAG}"
    else
        echo "Warning: .image-tag file not found, using 'local' tag"
        echo "Run ./scripts/minikube/04-build-images.sh first to generate timestamp-based tag"
        IMAGE_TAG="local"
    fi
    
    # Install using Helm with timestamp-based image tag
    helm upgrade --install "${subgraph}" "subgraphs/${subgraph}/deploy" \
        -f "$VALUES_FILE" \
        --set image.tag="${IMAGE_TAG}" \
        -n "${subgraph}" \
        --wait
    
    # Create Subgraph CRD with inline SDL
    echo "Creating Subgraph CRD for ${subgraph}..."
    
    SCHEMA_FILE="subgraphs/${subgraph}/schema.graphql"
    if [ ! -f "$SCHEMA_FILE" ]; then
        echo "Error: Schema file not found: $SCHEMA_FILE"
        exit 1
    fi
    
    SCHEMA_CONTENT=$(cat "$SCHEMA_FILE" | sed 's/^/      /')
    TEMP_TEMPLATE=$(mktemp)
    TEMP_SCHEMA=$(mktemp)
    echo "$SCHEMA_CONTENT" > "$TEMP_SCHEMA"
    sed "s/\${SUBGRAPH_NAME}/${subgraph}/g" deploy/operator-resources/subgraph.yaml.template > "$TEMP_TEMPLATE"
    sed "/\${SCHEMA_CONTENT}/r $TEMP_SCHEMA" "$TEMP_TEMPLATE" | sed '/\${SCHEMA_CONTENT}/d' | kubectl apply -f -
    rm -f "$TEMP_TEMPLATE" "$TEMP_SCHEMA"
    
    echo "✓ ${subgraph} deployed successfully"
done

# Deploy REST API services
for service in "${SERVICES[@]}"; do
    echo ""
    echo "Deploying ${service}..."
    
    kubectl create namespace "${service}" --dry-run=client -o yaml | kubectl apply -f -
    
    VALUES_FILE="services/${service}/deploy/values.yaml"
    if [ ! -f "$VALUES_FILE" ]; then
        echo "Error: Values file not found: $VALUES_FILE"
        exit 1
    fi
    
    if [ -f ".image-tag" ]; then
        IMAGE_TAG=$(head -n 1 .image-tag | tr -d '[:space:]')
    else
        IMAGE_TAG="local"
    fi
    
    helm upgrade --install "${service}" "services/${service}/deploy" \
        -f "$VALUES_FILE" \
        --set image.tag="${IMAGE_TAG}" \
        -n "${service}" \
        --wait
    
    echo "✓ ${service} deployed successfully"
done

# Create Subgraph CRDs for connector-only subgraphs (schema only, no Helm deployment)
for subgraph in "${CONNECTOR_SUBGRAPHS[@]}"; do
    echo ""
    echo "Creating Subgraph CRD for connector ${subgraph}..."
    
    kubectl create namespace "${subgraph}" --dry-run=client -o yaml | kubectl apply -f -
    
    SCHEMA_FILE="subgraphs/${subgraph}/schema.graphql"
    if [ ! -f "$SCHEMA_FILE" ]; then
        echo "Error: Schema file not found: $SCHEMA_FILE"
        exit 1
    fi
    
    SCHEMA_CONTENT=$(cat "$SCHEMA_FILE" | sed 's/^/      /')
    TEMP_TEMPLATE=$(mktemp)
    TEMP_SCHEMA=$(mktemp)
    echo "$SCHEMA_CONTENT" > "$TEMP_SCHEMA"
    sed "s/\${SUBGRAPH_NAME}/${subgraph}/g" deploy/operator-resources/subgraph.yaml.template > "$TEMP_TEMPLATE"
    # Connectors don't use a GraphQL endpoint - router executes connector logic directly.
    # Use placeholder URL per https://www.apollographql.com/docs/guides/onboarding/apis/connect-rest-apis
    sed "s|http://graphql.${subgraph}.svc.cluster.local:4001|http://ignore|g" "$TEMP_TEMPLATE" > "${TEMP_TEMPLATE}.tmp" && mv "${TEMP_TEMPLATE}.tmp" "$TEMP_TEMPLATE"
    sed "/\${SCHEMA_CONTENT}/r $TEMP_SCHEMA" "$TEMP_TEMPLATE" | sed '/\${SCHEMA_CONTENT}/d' | kubectl apply -f -
    rm -f "$TEMP_TEMPLATE" "$TEMP_SCHEMA"
    
    echo "✓ ${subgraph} connector schema registered"
done

echo ""
echo "✓ All subgraphs and services deployed!"
echo ""
echo "Monitor subgraph status with:"
echo "  kubectl get subgraphs --all-namespaces"
echo ""
echo "Next step: Run ./scripts/minikube/06-deploy-coprocessor.sh to deploy the coprocessor"
