#!/bin/bash
set -euo pipefail

# Script 08: Setup Router Access
# This script configures port-forwarding for the router service
# Port-forwarding is the only consistently working access method

# Ensure script is run from repository root
if [ ! -d "scripts/minikube" ] || [ ! -d "subgraphs" ] || [ ! -d "deploy" ]; then
    echo "Error: This script must be run from the repository root directory"
    echo "Please run: ./scripts/minikube/08-setup-router-access.sh"
    exit 1
fi

echo "=== Step 08: Setting Up Router Access ==="

# Load environment variables from .env if it exists
if [ -f .env ]; then
    echo "Loading environment variables from .env..."
    source .env
fi

# Validate required variables
if [[ -z "${ENVIRONMENT:-}" ]]; then
    echo "Error: ENVIRONMENT is required"
    echo "Please set ENVIRONMENT in your .env file or export it:"
    echo "  export ENVIRONMENT=\"dev\""
    exit 1
fi

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "Error: kubectl is not installed"
    exit 1
fi

# Verify cluster connection
if ! kubectl cluster-info &> /dev/null; then
    echo "Error: Cannot connect to Kubernetes cluster"
    exit 1
fi

# Check if router service exists
RESOURCE_NAME="reference-architecture-${ENVIRONMENT}"
if ! kubectl get service "$RESOURCE_NAME" -n apollo &> /dev/null; then
    echo "Error: Router service '$RESOURCE_NAME' not found in namespace 'apollo'"
    echo "Please ensure the router is deployed first"
    exit 1
fi

# Set router URL to use port-forwarding
# Apollo Router serves GraphQL at the root path (/), not /graphql
ROUTER_URL="http://localhost:4000/"
PORT_FORWARD_PORT=4000
PF_PID_FILE=".router-port-forward.pid"

# Clean up existing PID file and any stale process
if [ -f "$PF_PID_FILE" ]; then
    OLD_PID=$(cat "$PF_PID_FILE" 2>/dev/null | head -n 1 | tr -d '[:space:]' || echo "")
    if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
        echo "Found existing port-forward process (PID: $OLD_PID). Stopping it..."
        kill "$OLD_PID" 2>/dev/null || true
        sleep 2
    fi
    rm -f "$PF_PID_FILE"
fi

# Check if port-forward is already running on this port
if lsof -ti:${PORT_FORWARD_PORT} &> /dev/null; then
    echo "Port ${PORT_FORWARD_PORT} is already in use. Checking if it's a kubectl port-forward..."
    # Try to find kubectl port-forward processes for this service
    EXISTING_PF=$(ps aux | grep "kubectl port-forward.*${RESOURCE_NAME}.*${PORT_FORWARD_PORT}" | grep -v grep | awk '{print $2}' || echo "")
    if [ -n "$EXISTING_PF" ]; then
        echo "Found existing port-forward (PID: $EXISTING_PF). Stopping it..."
        kill $EXISTING_PF 2>/dev/null || true
        sleep 2
    else
        echo "Warning: Port ${PORT_FORWARD_PORT} is in use by another process"
        echo "Please free the port or use a different port"
        exit 1
    fi
fi

# Start port-forwarding in the background
echo "Starting port-forward for router service..."
nohup kubectl port-forward service/$RESOURCE_NAME -n apollo ${PORT_FORWARD_PORT}:80 > /dev/null 2>&1 &
PORT_FORWARD_PID=$!
# Disown the process so it continues after script exits
disown $PORT_FORWARD_PID 2>/dev/null || true

# Wait a moment for port-forward to establish
sleep 3

# Verify port-forward is running
if ! kill -0 $PORT_FORWARD_PID 2>/dev/null; then
    echo "Error: Port-forward failed to start"
    exit 1
fi

# Test if the port is accessible
if ! lsof -ti:${PORT_FORWARD_PORT} &> /dev/null; then
    echo "Warning: Port-forward started but port ${PORT_FORWARD_PORT} is not accessible"
    echo "Port-forward PID: $PORT_FORWARD_PID"
else
    echo "✓ Port-forward is running (PID: $PORT_FORWARD_PID)"
fi

# Save PID to a file for cleanup later
echo "$PORT_FORWARD_PID" > "$PF_PID_FILE"

# Save to .env file
ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    touch "$ENV_FILE"
fi

# Remove old ROUTER_URL if it exists and add new one
if grep -q "^export ROUTER_URL=" "$ENV_FILE"; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^export ROUTER_URL=.*|export ROUTER_URL=\"$ROUTER_URL\"|" "$ENV_FILE"
    else
        sed -i "s|^export ROUTER_URL=.*|export ROUTER_URL=\"$ROUTER_URL\"|" "$ENV_FILE"
    fi
else
    echo "" >> "$ENV_FILE"
    echo "# Router URL (generated by 08-setup-router-access.sh)" >> "$ENV_FILE"
    echo "export ROUTER_URL=\"$ROUTER_URL\"" >> "$ENV_FILE"
fi

# Output summary
echo ""
echo "✓ Router access configured successfully!"
echo ""
echo "Router URL: $ROUTER_URL (saved to .env)"
echo "Port-forward PID: $PORT_FORWARD_PID (saved to $PF_PID_FILE)"
echo ""
echo "The router is now accessible at: http://localhost:${PORT_FORWARD_PORT}/"
echo ""
echo "Note: The port-forward is running in the background."
echo "      To stop it: kill \$(cat $PF_PID_FILE)"
echo ""
echo "Next: Run ./scripts/minikube/09-deploy-client.sh to deploy the client application"


