#!/bin/bash
set -euo pipefail

# Script 08: Setup Router Access
# This script configures the ingress controller for the client application
# The ingress controller is needed for the client's Ingress resource (not the router)
# Note: The router does not use an Ingress resource - the client's nginx proxies to it internally

echo "=== Step 08: Setting Up Router Access ==="

# Load environment variables from .env if it exists
if [ -f .env ]; then
    echo "Loading environment variables from .env..."
    source .env
fi

# Validate required variables
if [[ -z "${ENVIRONMENT:-}" ]]; then
    echo "Error: ENVIRONMENT is required"
    echo "Please set ENVIRONMENT in your .env file or export it:"
    echo "  export ENVIRONMENT=\"dev\""
    exit 1
fi

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "Error: kubectl is not installed"
    exit 1
fi

# Verify cluster connection
if ! kubectl cluster-info &> /dev/null; then
    echo "Error: Cannot connect to Kubernetes cluster"
    exit 1
fi

# Check if ingress addon is enabled (required for client's Ingress resource)
if ! minikube addons list | grep -q "ingress.*enabled"; then
    echo "Enabling ingress addon (required for client application)..."
    minikube addons enable ingress
    echo "Waiting for ingress controller to be ready..."
    sleep 15
fi

# Wait for ingress controller pods to be ready
echo "Waiting for ingress controller to be ready..."
kubectl wait --namespace ingress-nginx \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/component=controller \
    --timeout=120s || {
    echo "Warning: Ingress controller may not be fully ready"
}

# Change ingress controller service to LoadBalancer for minikube tunnel support
echo "Configuring ingress controller for minikube tunnel..."
kubectl patch svc ingress-nginx-controller -n ingress-nginx -p '{"spec":{"type":"LoadBalancer"}}' 2>/dev/null || true

# Get router URL - use localhost for minikube tunnel (LoadBalancer) or NodePort fallback
MINIKUBE_IP=$(minikube ip)
INGRESS_NODEPORT=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}' 2>/dev/null || echo "")
INGRESS_TYPE=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.type}' 2>/dev/null || echo "")

# Determine router URL based on ingress type
if [ "$INGRESS_TYPE" == "LoadBalancer" ]; then
    ROUTER_URL="http://127.0.0.1/graphql"
elif [ -n "$INGRESS_NODEPORT" ]; then
    ROUTER_URL="http://${MINIKUBE_IP}:${INGRESS_NODEPORT}/graphql"
else
    ROUTER_URL="http://localhost:4000/graphql"
fi

# Save to .env file
ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    touch "$ENV_FILE"
fi

# Remove old ROUTER_URL if it exists and add new one
if grep -q "^export ROUTER_URL=" "$ENV_FILE"; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^export ROUTER_URL=.*|export ROUTER_URL=\"$ROUTER_URL\"|" "$ENV_FILE"
    else
        sed -i "s|^export ROUTER_URL=.*|export ROUTER_URL=\"$ROUTER_URL\"|" "$ENV_FILE"
    fi
else
    echo "" >> "$ENV_FILE"
    echo "# Router URL (generated by 08-setup-router-access.sh)" >> "$ENV_FILE"
    echo "export ROUTER_URL=\"$ROUTER_URL\"" >> "$ENV_FILE"
fi

# Output summary
echo ""
echo "✓ Router access configured successfully!"
echo ""
echo "Router URL: $ROUTER_URL (saved to .env)"
echo ""

if [ "$INGRESS_TYPE" == "LoadBalancer" ]; then
    echo "⚠️  Next step: Run 'minikube tunnel' in a separate terminal to access the router"
    echo ""
    echo "Access methods:"
    echo "  1. minikube tunnel (recommended):"
    echo "     • Run: minikube tunnel"
    echo "     • If it hangs, check if tunnel is already running: ps aux | grep 'minikube tunnel'"
    echo "     • Stop existing tunnel: pkill -f 'minikube tunnel'"
    echo "     • Access client UI at: http://127.0.0.1/"
    echo "     • GraphQL requests proxied via /graphql"
    if [ -n "$INGRESS_NODEPORT" ]; then
        echo ""
        echo "  2. NodePort (no tunnel needed):"
        echo "     • Client UI: http://${MINIKUBE_IP}:${INGRESS_NODEPORT}/"
        echo "     • Update .env: export ROUTER_URL=\"http://${MINIKUBE_IP}:${INGRESS_NODEPORT}/graphql\""
    fi
    echo ""
    echo "  3. Port forward (no tunnel needed):"
    echo "     • Run: kubectl port-forward service/reference-architecture-${ENVIRONMENT} -n apollo 4000:80"
    echo "     • Update .env: export ROUTER_URL=\"http://localhost:4000/graphql\""
else
    echo "Access methods:"
    echo "  1. NodePort: http://${MINIKUBE_IP}:${INGRESS_NODEPORT}"
    echo "  2. Port forward: kubectl port-forward service/reference-architecture-${ENVIRONMENT} -n apollo 4000:80"
fi

echo ""
echo "Next: Run 09-deploy-client.sh to deploy the client application"
echo "      (Required for ingress access; optional if using port-forward)"


