apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  labels: {{- include "collector.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      zipkin:
        endpoint: "http://zipkin.zipkin.svc.cluster.local:9411/api/v2/spans"
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [zipkin]
