apiVersion: v1
kind: Service
metadata:
  name: {{ include "collector.fullname" . }}
  labels: {{- include "collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: metrics-grpc
      port: 4317
      protocol: TCP
      name: metrics-grpc
    - targetPort: metrics-http
      port: 4318
      protocol: TCP
      name: metrics-http
    - targetPort: metrics-prom
      port: 8888
      protocol: TCP
      name: metrics-prom
  selector: {{- include "collector.selectorLabels" . | nindent 4 }}
