name: _deploy-client-gke

# Started from GH Docs
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: main
        required: true
      dry-run:
        type: boolean
        description: Run a dry run with helm
        required: false
        default: false
      debug:
        type: boolean
        description: Run helm in debug mode
        required: false
        default: false
    secrets:
      GCP_CREDENTIALS:
        required: true
      CLUSTER_PREFIX:
        required: true

env:
  IMAGE: ${{ github.repository }}/client
  GKE_ZONE: us-east1
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v0

      - name: "Use gcloud CLI"
        run: gcloud info

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.CLUSTER_PREFIX }}-prod
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster with dry run
     # Deploy the Docker image to the GKE cluster with dry run
      - name: Helm dry-run
        if: ${{ inputs.dry-run }}
        run: |
          repository=$(echo "$REGISTRY/$IMAGE" | tr '[:upper:]' '[:lower:]')

          helm upgrade client \
          --create-namespace \
          --namespace client \
          --set image.repository=$repository \
          --set image.tag=${{ inputs.version }} \
          --dry-run \
          --atomic \
          --install \
          --timeout 60s \
          ./deploy/client \
          --values ./deploy/client/values.yaml \

      # Deploy the Docker image to the GKE cluster for real with debug
      - name: Deploy
        if: ${{ !inputs.dry-run && inputs.debug }}
        run: |
          repository=$(echo "$REGISTRY/$IMAGE" | tr '[:upper:]' '[:lower:]')

          helm upgrade client \
          --create-namespace \
          --namespace client \
          --set image.repository=$repository \
          --set image.tag=${{ inputs.version }} \
          --atomic \
          --install \
          --timeout 60s \
          --debug \
          ./deploy/client \
          --values ./deploy/client/values.yaml \

      # Deploy the Docker image to the GKE cluster for real
      - name: Deploy
        if: ${{ !inputs.dry-run }}
        run: |
          repository=$(echo "$REGISTRY/$IMAGE" | tr '[:upper:]' '[:lower:]')

          helm upgrade client \
          --create-namespace \
          --namespace client \
          --set image.repository=$repository \
          --set image.tag=${{ inputs.version }} \
          --atomic \
          --install \
          --timeout 60s \
          ./deploy/client \
          --values ./deploy/client/values.yaml \
