name: _rover-client-pq-publish

on:
  workflow_call:
    inputs:
      environment:
        description: "Target variant"
        type: string
        required: true
        default: dev
    secrets:
      APOLLO_KEY:
        required: true
      APOLLO_GRAPH_ID:
        required: true

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}

jobs:
  check:
    name: Rover PQ Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rover
        uses: apollographql-gh-actions/install-rover@v1

      - name: Generate PQ manifest
        run: |
          cd ./client/
          npx @apollo/generate-persisted-query-manifest 
          
      - name: Publish PQ Manifest
        uses: apollographql-gh-actions/rover-persisted-queries-publish@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ secrets.APOLLO_GRAPH_ID }}@${{ inputs.environment }}
          manifest: ./client/persisted-query-manifest.json
        