name: Deploy Client

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
      dry-run:
        type: boolean
        description: "Run a dry run with helm"
        required: false
        default: false
      debug:
        type: boolean
        description: "Run helm in debug mode"
        required: false
        default: false

jobs:
  determine_cloud_provider:
    uses: ./.github/workflows/_determine-provider.yaml
    secrets: inherit

  publish_pqs: 
    if: needs.determine_cloud_provider.outputs.apollo == 'true'
    needs: [determine_cloud_provider]
    uses: ./.github/workflows/_rover-client-pq-publish.yml
    secrets: inherit
    with:
      environment: prod
  
  deploy_gcp:
    if: needs.determine_cloud_provider.outputs.gcp == 'true'
    needs: [determine_cloud_provider, publish_pqs]
    uses: ./.github/workflows/_deploy-client-gke.yaml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run }}
      debug: ${{ inputs.debug }}
      version: main

  deploy_aws:
    if: needs.determine_cloud_provider.outputs.aws == 'true'
    needs: [determine_cloud_provider, publish_pqs]
    uses: ./.github/workflows/_deploy-client-aws.yaml
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run }}
      debug: ${{ inputs.debug }}
      version: main
