name: Merge to Main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  determine_cloud_provider:
    uses: ./.github/workflows/_determine-provider.yaml
    secrets: inherit

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        subgraph: [checkout, discovery, inventory, orders, products, reviews, shipping, users]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.subgraph }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./subgraphs/${{ matrix.subgraph }}
          file: ./subgraphs/${{ matrix.subgraph }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_gcp:
    if: needs.determine_cloud_provider.outputs.gcp == 'true'
    needs: [determine_cloud_provider, build-and-push-image]
    uses: ./.github/workflows/_deploy-gke.yaml
    secrets: inherit
    strategy:
      matrix:
        subgraph: [checkout, discovery, inventory, orders, products, reviews, shipping, users]
    with:
      version: main
      app_name: ${{ matrix.subgraph }}
      cluster_suffix: dev

  deploy_aws:
    if: needs.determine_cloud_provider.outputs.aws == 'true'
    needs: [determine_cloud_provider, build-and-push-image]
    uses: ./.github/workflows/_deploy-aws.yaml
    secrets: inherit
    strategy:
      matrix:
        subgraph: [checkout, discovery, inventory, orders, products, reviews, shipping, users]
    with:
      version: main
      app_name: ${{ matrix.subgraph }}
      cluster_suffix: dev
      region: us-east-1

  publish:
    needs: [deploy_aws, deploy_gcp]
    strategy:
      matrix:
        subgraph: [checkout, discovery, inventory, orders, products, reviews, shipping, users]
    if: always() &&
      (needs.deploy_aws.result == 'success' || needs.deploy_aws.result == 'skipped') &&
      (needs.deploy_gcp.result == 'success' || needs.deploy_gcp.result == 'skipped')
    uses: ./.github/workflows/_rover-subgraph-publish.yml
    secrets: inherit
    with:
      subgraph_name: ${{ matrix.subgraph }} # change to subgraph-b in that repo
      variant: dev